environment:
  qnn_sdk_root: /root/autodl-tmp/zgj/tools/qairt/2.42.0.251225
  compute_device: cuda
  cpu_device: cpu
  omp_num_threads: 1
  tokenizers_parallelism: "0"

model:
  name: qwen25llm
  model_id: /root/autodl-tmp/zgj/Qwen25/models/Qwen2.5-VL-3B-Instruct
  cache_dir: /root/autodl-tmp/zgj/Qwen25/outputs/cache
  output_dir: /root/autodl-tmp/zgj/Qwen25/outputs/output
  context_length: 2048
  arn: 1073
  enable_fp16: false
  tokenizer_use_fast: true
  trust_remote_code: true
  mask_neg:
    fp16: -50
    fp32: -100
  config_overrides:
    return_new_key_value_only: true
    transposed_key_cache: true
    use_combined_mask_input: true
    use_position_embedding_input: true
    use_cache: true
    _attn_implementation: eager
    _attn_implementation_internal: eager
    pretraining_tp: 1
    use_input_embeddings: true
    use_mrope: false

dataset:
  wiki:
    path: wikitext
    name: wikitext-2-raw-v1
    train_split: train
    test_split: test
    batch_size: 1
    shuffle: false
  vl:
    img_h: 672
    img_w: 336
    emb_length: null
    device: null
    qwen2vl_model_path: null
    calibration_dataset_path: /root/autodl-tmp/zgj/data/llava_v1_5_mix665k.json
    ppl_evaluation_dataset_path: /root/autodl-tmp/zgj/data/llava_v1_5_mix665k.json
    image_dataset_path: /root/autodl-tmp/zgj/data
    default_image_path: coco/train2017/000000000025.jpg
    R1_path: null
    num_test_batches: 100
    batch_size: 1
    shuffle: false

evaluation:
  original_ppl_batches: 10
  prepared_ppl_batches: 10
  sim_ppl_batches: 10

prepare:
  skip_prepare: true
  export_to_onnx_direct: true
  keep_original_model_structure: false
  converter_args_value: NONTRIVIAL
  onnx_export_opset: 20

quantization:
  htp_config_file: htp_v73
  quant_scheme: post_training_tf
  default_output_bw: 16
  default_param_bw: 4
  in_place: true
  mixed_precision_config_file: ./config/mixed_precision_config/exceptions.json

seq_mse:
  num_batches: 20
  inp_symmetry: symqt
  num_candidates: 20
  loss_fn: mse

encoding:
  num_batches: 20

test_vectors:
  num_batches: 1
  layers:
    - model_layers_\d+_input_layernorm_Pow
    - model_layers_\d+_Add_1
    - rms_norm_\d+

export:
  onnx_dir_name: onnx
  onnx_opset_version: 14
